import { Suspense } from "react";
import CategoryList from "../_components/CategoryList";
import CategoryListLoading from "../_components/CategoryListLoading";
import Image from "next/image";
import PostListLoading from "../_components/PostListLoading";
import Search from "@/ui/Search";
import CategoryListMobile from "../_components/CategoryListMobile";
import SortFilter from "../_components/SortFilter";

export const metadata = {
    title: "بلاگ ها",
    description: "Generated by create next app",
};

function Layout({ children }) {
    return (
        <div className="w-full grid grid-cols-1 lg:grid-cols-24 gap-6 mt-14 mb-20 relative items-start">
            <div className="hidden lg:flex lg:col-span-7 xl:col-span-6 flex-col gap-4 sticky top-6 right-0">
                <Search />
                <Suspense fallback={<CategoryListLoading />}>
                    <CategoryList />
                </Suspense>
                <SortFilter />
            </div>
            <div className="w-full col-span-full lg:col-span-17 xl:col-span-18">
                <div className="pb-8 pr-2 flex items-center gap-3">
                    <Image
                        src={'/images/blog-pic.png'}
                        alt="مقالات"
                        width={50}
                        height={50}
                    />
                    <h1 className="text-4xl font-black text-primary-900 ">
                        مقالات
                    </h1>
                </div>
                <div className="lg:hidden pb-6">
                    <Search />
                    <div className="pt-3 flex items-center gap-3">
                        <CategoryListMobile />
                        <SortFilter />
                    </div>
                </div>
                <Suspense fallback={<PostListLoading />}>
                    {children}
                </Suspense>
            </div>
        </div>
    )
}

export default Layout
