import { Suspense } from "react";
import CategoryList from "../_components/CategoryList";
import CategoryListLoading from "../_components/CategoryListLoading";

export const metadata = {
    title: "بلاگ ها",
    description: "Generated by create next app",
};

function Layout({ children }) {
    return (
        <div className="w-full grid grid-cols-1  lg:grid-cols-24 gap-6 mt-14 mb-20">
            <div className="hidden lg:inline-block lg:col-span-7 xl:col-span-6">
                <Suspense fallback={<CategoryListLoading />}>
                    <CategoryList />
                </Suspense>
            </div>
            <div className="w-full col-span-full lg:col-span-17 xl:col-span-18">
                {children}
            </div>
        </div>
    )
}

export default Layout
